var searchData=
[
  ['s_5fformatter_0',['S_formatter',['../classspdlog_1_1details_1_1_s__formatter.html',1,'spdlog::details']]],
  ['scoped_5fpadder_1',['scoped_padder',['../classspdlog_1_1details_1_1scoped__padder.html',1,'spdlog::details']]],
  ['short_5ffilename_5fformatter_2',['short_filename_formatter',['../classspdlog_1_1details_1_1short__filename__formatter.html',1,'spdlog::details']]],
  ['short_5flevel_5fformatter_3',['short_level_formatter',['../classspdlog_1_1details_1_1short__level__formatter.html',1,'spdlog::details']]],
  ['sid_5ft_4',['sid_t',['../structspdlog_1_1sinks_1_1win__eventlog_1_1internal_1_1sid__t.html',1,'spdlog::sinks::win_eventlog::internal']]],
  ['singleton_5',['singleton',['../structdetail_1_1singleton.html',1,'detail']]],
  ['sink_6',['sink',['../classspdlog_1_1sinks_1_1sink.html',1,'spdlog::sinks']]],
  ['source_5ffilename_5fformatter_7',['source_filename_formatter',['../classspdlog_1_1details_1_1source__filename__formatter.html',1,'spdlog::details']]],
  ['source_5ffuncname_5fformatter_8',['source_funcname_formatter',['../classspdlog_1_1details_1_1source__funcname__formatter.html',1,'spdlog::details']]],
  ['source_5flinenum_5fformatter_9',['source_linenum_formatter',['../classspdlog_1_1details_1_1source__linenum__formatter.html',1,'spdlog::details']]],
  ['source_5floc_10',['source_loc',['../structspdlog_1_1source__loc.html',1,'spdlog']]],
  ['source_5flocation_5fformatter_11',['source_location_formatter',['../classspdlog_1_1details_1_1source__location__formatter.html',1,'spdlog::details']]],
  ['span_12',['span',['../structdetail_1_1span.html',1,'detail']]],
  ['spdlog_5fex_13',['spdlog_ex',['../classspdlog_1_1spdlog__ex.html',1,'spdlog']]],
  ['std_5fstring_5fview_14',['std_string_view',['../structdetail_1_1std__string__view.html',1,'detail']]],
  ['stderr_5fsink_15',['stderr_sink',['../classspdlog_1_1sinks_1_1stderr__sink.html',1,'spdlog::sinks']]],
  ['stderr_5fsink_3c_20details_3a_3aconsole_5fmutex_20_3e_16',['stderr_sink&lt; details::console_mutex &gt;',['../classspdlog_1_1sinks_1_1stderr__sink.html',1,'spdlog::sinks']]],
  ['stderr_5fsink_3c_20details_3a_3aconsole_5fnullmutex_20_3e_17',['stderr_sink&lt; details::console_nullmutex &gt;',['../classspdlog_1_1sinks_1_1stderr__sink.html',1,'spdlog::sinks']]],
  ['stdout_5fsink_18',['stdout_sink',['../classspdlog_1_1sinks_1_1stdout__sink.html',1,'spdlog::sinks']]],
  ['stdout_5fsink_3c_20details_3a_3aconsole_5fmutex_20_3e_19',['stdout_sink&lt; details::console_mutex &gt;',['../classspdlog_1_1sinks_1_1stdout__sink.html',1,'spdlog::sinks']]],
  ['stdout_5fsink_3c_20details_3a_3aconsole_5fnullmutex_20_3e_20',['stdout_sink&lt; details::console_nullmutex &gt;',['../classspdlog_1_1sinks_1_1stdout__sink.html',1,'spdlog::sinks']]],
  ['stdout_5fsink_5fbase_21',['stdout_sink_base',['../classspdlog_1_1sinks_1_1stdout__sink__base.html',1,'spdlog::sinks']]],
  ['stopwatch_22',['stopwatch',['../classspdlog_1_1stopwatch.html',1,'spdlog']]],
  ['streamed_5fview_23',['streamed_view',['../structdetail_1_1streamed__view.html',1,'detail']]],
  ['string_5fliteral_24',['string_literal',['../structdetail_1_1string__literal.html',1,'detail']]],
  ['string_5fvalue_25',['string_value',['../structdetail_1_1string__value.html',1,'detail']]],
  ['string_5fvalue_3c_20char_5ftype_20_3e_26',['string_value&lt; char_type &gt;',['../structdetail_1_1string__value.html',1,'detail']]],
  ['strip_5fnamed_5farg_27',['strip_named_arg',['../structdetail_1_1strip__named__arg.html',1,'detail']]],
  ['strip_5fnamed_5farg_3c_20t_2c_20true_20_3e_28',['strip_named_arg&lt; T, true &gt;',['../structdetail_1_1strip__named__arg_3_01_t_00_01true_01_4.html',1,'detail']]],
  ['styled_5farg_29',['styled_arg',['../structdetail_1_1styled__arg.html',1,'detail']]],
  ['synchronous_5ffactory_30',['synchronous_factory',['../structspdlog_1_1synchronous__factory.html',1,'spdlog']]],
  ['syslog_5fsink_31',['syslog_sink',['../classspdlog_1_1sinks_1_1syslog__sink.html',1,'spdlog::sinks']]],
  ['syslog_5fsink_3c_20details_3a_3anull_5fmutex_20_3e_32',['syslog_sink&lt; details::null_mutex &gt;',['../classspdlog_1_1sinks_1_1syslog__sink.html',1,'spdlog::sinks']]],
  ['syslog_5fsink_3c_20std_3a_3amutex_20_3e_33',['syslog_sink&lt; std::mutex &gt;',['../classspdlog_1_1sinks_1_1syslog__sink.html',1,'spdlog::sinks']]],
  ['systemd_5fsink_34',['systemd_sink',['../classspdlog_1_1sinks_1_1systemd__sink.html',1,'spdlog::sinks']]],
  ['systemd_5fsink_3c_20details_3a_3anull_5fmutex_20_3e_35',['systemd_sink&lt; details::null_mutex &gt;',['../classspdlog_1_1sinks_1_1systemd__sink.html',1,'spdlog::sinks']]],
  ['systemd_5fsink_3c_20std_3a_3amutex_20_3e_36',['systemd_sink&lt; std::mutex &gt;',['../classspdlog_1_1sinks_1_1systemd__sink.html',1,'spdlog::sinks']]]
];
